language: node_js
node_js: stable

install:
  - npm install -g hexo

script:
  - hexo g

after_script:
  - mkdir public
  - cd ./public
  - git init
  - git config user.name "caticat"
  - git comfig user.email "catifish@163.com"
  - echo "Hello World<br/>" >> index.html
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - source

env:
  global:
    - GH_REF: github.com/caticat/caticat.github.io.git
